services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: lpnuser
      POSTGRES_PASSWORD: lpnpassword
      POSTGRES_DB: lpn
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  pgdata:
